import { sqliteTable, text, integer, primaryKey } from "drizzle-orm/sqlite-core";
import { sql } from "drizzle-orm";
import { user, session, account, verification } from "./auth-schema.js";

const id = () => text("id").primaryKey().$defaultFn(() => crypto.randomUUID());
const timestamps = {
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
};

// ---------------------------------------------------------------------------
// Identity - brief §3.8/§3.18, RESOLVED this pass: better-auth owns identity
// entirely rather than a parallel custom `users` table. `user` is generated by
// `npx @better-auth/cli generate` (see auth-schema.ts) with `isAdmin` folded in
// as an additionalField (auth/config.ts) - not hand-maintained here. `account`
// is better-auth's own multi-provider-per-user table, which is exactly what the
// brief called `identities` (password + Google + GitHub all resolving to one
// user via separate `account` rows). `session` replaces our custom `sessions`.
// Re-exported under the names the rest of this schema (and the brief) uses, so
// every other table's `.references(() => users.id)` below only needed a single
// import change, not a rename throughout the codebase.
// ---------------------------------------------------------------------------
const users = user;
const sessions = session;
const identities = account;
export { users, sessions, identities, verification };

// ---------------------------------------------------------------------------
// Groups - the SOLE permission-granting mechanism (brief §3.8 / §3.18: an earlier
// individual page_permissions table was dropped in favor of groups-only, precisely
// to avoid two overlapping grant paths with no stated precedence).
// ---------------------------------------------------------------------------
export const groups = sqliteTable("groups", {
  id: id(),
  name: text("name").notNull().unique(),
  ...timestamps,
});

// Missing from the reviewed handoff despite being in its own design doc - added here.
export const userGroups = sqliteTable("user_groups", {
  userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  groupId: text("group_id").notNull().references(() => groups.id, { onDelete: "cascade" }),
}, (t) => ({
  pk: primaryKey({ columns: [t.userId, t.groupId] }),
}));

// ---------------------------------------------------------------------------
// Spaces - brief §3.8. Also missing from the reviewed handoff (space_members,
// space_group_permissions) - added here; the algorithm's "space fallback" step
// has nothing to fall back to without these.
// ---------------------------------------------------------------------------
export const spaces = sqliteTable("spaces", {
  id: id(),
  name: text("name").notNull(),
  createdBy: text("created_by").notNull().references(() => users.id),
  ...timestamps,
});

export const spaceMembers = sqliteTable("space_members", {
  spaceId: text("space_id").notNull().references(() => spaces.id, { onDelete: "cascade" }),
  userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  role: text("role", { enum: ["viewer", "editor", "admin"] }).notNull(),
}, (t) => ({
  pk: primaryKey({ columns: [t.spaceId, t.userId] }),
}));

export const spaceGroupPermissions = sqliteTable("space_group_permissions", {
  id: id(),
  spaceId: text("space_id").notNull().references(() => spaces.id, { onDelete: "cascade" }),
  groupId: text("group_id").notNull().references(() => groups.id, { onDelete: "cascade" }),
  role: text("role", { enum: ["viewer", "editor", "admin"] }).notNull(),
});

// ---------------------------------------------------------------------------
// Pages + branches - the core data model, brief §3.1 / §3.1a.
// Content lives on `pages` (authorship, one row per abstract piece of content).
// Placement, space, and visibility live on `branches` (§3.1's critical fix -
// these were originally on pages, which broke the moment a page was cloned
// across two spaces with different security contexts).
// ---------------------------------------------------------------------------
export const pages = sqliteTable("pages", {
  id: id(),
  slug: text("slug").notNull(), // added this revision - was missing from the reviewed handoff's own doc
  content: text("content", { mode: "json" }).notNull().default(sql`'{"type":"doc","content":[{"type":"paragraph"}]}'`), // Tiptap/ProseMirror JSON - must contain at least one block node, an empty content array isn't a valid document
  ownerId: text("owner_id").notNull().references(() => users.id),
  deletedAt: integer("deleted_at", { mode: "timestamp_ms" }),
  ...timestamps,
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const branches = sqliteTable("branches", {
  id: id(),
  pageId: text("page_id").notNull().references(() => pages.id, { onDelete: "cascade" }),
  parentBranchId: text("parent_branch_id").references((): any => branches.id),
  position: integer("position").notNull().default(0),
  spaceId: text("space_id").notNull().references(() => spaces.id, { onDelete: "cascade" }),
  visibility: text("visibility", { enum: ["inherit", "public", "private"] }).notNull().default("inherit"),
  isSystem: integer("is_system", { mode: "boolean" }).notNull().default(false), // Trash, etc. - §3.1a
  createdBy: text("created_by").notNull().references(() => users.id),
  ...timestamps,
});

// Branch-level permission grants - "local boundaries", brief §3.8. Never 'admin' -
// managing membership/permissions stays space-scoped, not delegable per-branch.
export const groupPermissions = sqliteTable("group_permissions", {
  id: id(),
  branchId: text("branch_id").notNull().references(() => branches.id, { onDelete: "cascade" }),
  groupId: text("group_id").notNull().references(() => groups.id, { onDelete: "cascade" }),
  role: text("role", { enum: ["viewer", "editor"] }).notNull(),
});

// ---------------------------------------------------------------------------
// Comments - brief §7.6. Threads are anchored to a text range on a page;
// individual replies live in the comments table. The range is stored as
// {from, to} ProseMirror positions — the Comment extension stores these as
// marks so they're embedded in the Tiptap JSON; the DB copy is the
// authoritative record for rendering the sidebar panel independent of content.
// Since Phase 1 (§7.12) every block node carries an `id` attribute, so a thread
// is ALSO anchored to the containing block id: when earlier edits shift the
// character range, the highlight can be re-anchored to the block's current
// range instead of drifting into unrelated text.
// ---------------------------------------------------------------------------
export const commentThreads = sqliteTable("comment_threads", {
  id: id(),
  pageId: text("page_id").notNull().references(() => pages.id, { onDelete: "cascade" }),
  blockId: text("block_id"),
  rangeFrom: integer("range_from").notNull(),
  rangeTo: integer("range_to").notNull(),
  // The exact text the thread is anchored to, captured at creation time
  // (mirrors Docmost's comment `selection` field). Lets the comment panel show
  // what a note references even when the highlight range has drifted.
  selection: text("selection"),
  resolvedAt: integer("resolved_at", { mode: "timestamp_ms" }),
  resolvedBy: text("resolved_by").references(() => users.id),
  createdBy: text("created_by").notNull().references(() => users.id),
  ...timestamps,
});

export const comments = sqliteTable("comments", {
  id: id(),
  threadId: text("thread_id").notNull().references(() => commentThreads.id, { onDelete: "cascade" }),
  body: text("body").notNull(),
  userId: text("user_id").notNull().references(() => users.id),
  ...timestamps,
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

// ---------------------------------------------------------------------------
// Files - brief §3.13a. Served with branch-context (not just file id) so a page
// cloned into multiple security contexts can't be used to view a private file
// via its public clone's ID.
// ---------------------------------------------------------------------------
export const files = sqliteTable("files", {
  id: id(),
  pageId: text("page_id").notNull().references(() => pages.id, { onDelete: "cascade" }),
  filename: text("filename").notNull(),
  mimeType: text("mime_type").notNull(),
  sizeBytes: integer("size_bytes").notNull(),
  storagePath: text("storage_path").notNull(),
  uploadedBy: text("uploaded_by").notNull().references(() => users.id),
  ...timestamps,
});

// ---------------------------------------------------------------------------
// Templates - brief §3.18, adopted from the other session as a small, low-risk
// addition: pages usable as blueprints for new pages.
// ---------------------------------------------------------------------------
export const templates = sqliteTable("templates", {
  id: id(),
  pageId: text("page_id").notNull().references(() => pages.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  scope: text("scope", { enum: ["global", "user"] }).notNull(),
  createdBy: text("created_by").notNull().references(() => users.id),
  ...timestamps,
});

// ---------------------------------------------------------------------------
// Tokens - brief §3.10. Unified share-link + API token engine. scope_id is a
// BRANCH id (not a bare page id) when scope_type='branch' - a page can have
// multiple placements, each with its own security context (§3.1's fix again).
// ---------------------------------------------------------------------------
export const tokens = sqliteTable("tokens", {
  id: id(),
  type: text("type", { enum: ["share_link", "api_token"] }).notNull(),
  tokenHash: text("token_hash").notNull().unique(), // SHA-256; raw value shown once, never stored
  createdBy: text("created_by").notNull().references(() => users.id),
  name: text("name"),
  scopeType: text("scope_type", { enum: ["branch", "space", "account"] }).notNull(),
  scopeId: text("scope_id"), // branch id, space id, or null for account scope
  permission: text("permission", { enum: ["view", "edit", "admin"] }).notNull(),
  passwordHash: text("password_hash"), // optional, for password-protected share links
  expiresAt: integer("expires_at", { mode: "timestamp_ms" }),
  revokedAt: integer("revoked_at", { mode: "timestamp_ms" }),
  lastAccessedAt: integer("last_accessed_at", { mode: "timestamp_ms" }),
  warningCount: integer("warning_count").notNull().default(0),
  lastWarningAt: integer("last_warning_at", { mode: "timestamp_ms" }),
  ...timestamps,
});

// ---------------------------------------------------------------------------
// Background jobs (§ build order Phase 1) - Git commits, watchdog warnings, etc.
// ---------------------------------------------------------------------------
export const jobQueue = sqliteTable("job_queue", {
  id: id(),
  kind: text("kind").notNull(), // 'git_commit' | 'link_watchdog' | ...
  payload: text("payload", { mode: "json" }).notNull(),
  status: text("status", { enum: ["pending", "running", "done", "failed"] }).notNull().default("pending"),
  attempts: integer("attempts").notNull().default(0),
  runAfter: integer("run_after", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  ...timestamps,
});

// System/debug log - deliberately separate from the security audit log (brief
// §3.16: conflating the two would flood a security log with routine noise).
export const systemLogs = sqliteTable("system_logs", {
  id: id(),
  level: text("level", { enum: ["debug", "info", "warn", "error"] }).notNull(),
  source: text("source").notNull(),
  message: text("message").notNull(),
  meta: text("meta", { mode: "json" }),
  ...timestamps,
});

// Security-relevant audit log - auth events, permission/group/space changes,
// exports, share-link creation, plugin installs, sync runs. Phase 6 in the build
// order, table defined now so nothing has to migrate around it later.
export const auditLog = sqliteTable("audit_log", {
  id: id(),
  actorUserId: text("actor_user_id").references(() => users.id),
  action: text("action").notNull(), // 'login' | 'permission_grant' | 'export' | 'share_link_create' | ...
  targetType: text("target_type"), // 'branch' | 'space' | 'user' | 'token' | ...
  targetId: text("target_id"),
  meta: text("meta", { mode: "json" }),
  ...timestamps,
});

// ---------------------------------------------------------------------------
// Settings - brief §3.9. Admin-only system-wide config vs. per-person
// preferences. Secret values (OAuth client secrets, email API keys) are
// encrypted at rest by settings.service.ts before ever reaching this table -
// `isSecret` just tells the service/UI which values to mask, it doesn't do the
// encrypting itself.
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Backlinks — Phase 4 (§7.12 block-refs + backlinks). Each row records a link
// from one page to another (optionally to a specific block). Updated on every
// page save via scan-and-upsert - no stale-link cleanup, just fresh scan each
// write. The UI reads this table directly; no incremental maintenance.
// ---------------------------------------------------------------------------
export const backlinks = sqliteTable("backlinks", {
  sourcePageId: text("source_page_id").notNull().references(() => pages.id, { onDelete: "cascade" }),
  targetBranchId: text("target_branch_id").notNull(),
  targetBlockId: text("target_block_id"),
});
export const systemSettings = sqliteTable("system_settings", {
  key: text("key").primaryKey(),
  value: text("value", { mode: "json" }).notNull(),
  isSecret: integer("is_secret", { mode: "boolean" }).notNull().default(false),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  updatedBy: text("updated_by").references(() => users.id),
});

export const userSettings = sqliteTable("user_settings", {
  userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  key: text("key").notNull(),
  value: text("value", { mode: "json" }).notNull(),
}, (t) => ({
  pk: primaryKey({ columns: [t.userId, t.key] }),
}));

// ---------------------------------------------------------------------------
// Attributes — label/value pairs on pages (Trilium-style promoted labels)
// §7.12d.2 — isPromoted controls whether the attr surfaces in the editor sidebar.
// ---------------------------------------------------------------------------
export const attributes = sqliteTable("attributes", {
  id: id(),
  pageId: text("page_id").notNull().references(() => pages.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  value: text("value").notNull().default(""),
  isPromoted: integer("is_promoted", { mode: "boolean" }).notNull().default(false),
  position: integer("position").notNull().default(0),
  ...timestamps,
});
