/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedHealthRouteImport } from './routes/_authenticated/health'
import { Route as AuthenticatedPinnedRouteImport } from './routes/_authenticated/pinned'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as AuthenticatedLensesIndexRouteImport } from './routes/_authenticated/lenses/index'
import { Route as AuthenticatedLensesLensIdRouteImport } from './routes/_authenticated/lenses/$lensId'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsDangerRouteImport } from './routes/_authenticated/settings/danger'
import { Route as AuthenticatedSettingsGroupsRouteImport } from './routes/_authenticated/settings/groups'
import { Route as AuthenticatedSettingsIntegrationsRouteImport } from './routes/_authenticated/settings/integrations'
import { Route as AuthenticatedSettingsMaintenanceRouteImport } from './routes/_authenticated/settings/maintenance'
import { Route as AuthenticatedSettingsPluginsRouteImport } from './routes/_authenticated/settings/plugins'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings/profile'
import { Route as AuthenticatedSettingsSpacesRouteImport } from './routes/_authenticated/settings/spaces'
import { Route as AuthenticatedSettingsSystemRouteImport } from './routes/_authenticated/settings/system'
import { Route as AuthenticatedSettingsTokensRouteImport } from './routes/_authenticated/settings/tokens'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated/settings/users'
import { Route as AuthenticatedTrashSpaceIdRouteImport } from './routes/_authenticated/trash/$spaceId'
import { Route as AuthenticatedWBranchIdRouteImport } from './routes/_authenticated/w/$branchId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHealthRoute = AuthenticatedHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPinnedRoute = AuthenticatedPinnedRouteImport.update({
  id: '/pinned',
  path: '/pinned',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedLensesIndexRoute =
  AuthenticatedLensesIndexRouteImport.update({
    id: '/lenses/',
    path: '/lenses/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLensesLensIdRoute =
  AuthenticatedLensesLensIdRouteImport.update({
    id: '/lenses/$lensId',
    path: '/lenses/$lensId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsDangerRoute =
  AuthenticatedSettingsDangerRouteImport.update({
    id: '/danger',
    path: '/danger',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsGroupsRoute =
  AuthenticatedSettingsGroupsRouteImport.update({
    id: '/groups',
    path: '/groups',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsIntegrationsRoute =
  AuthenticatedSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsMaintenanceRoute =
  AuthenticatedSettingsMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsPluginsRoute =
  AuthenticatedSettingsPluginsRouteImport.update({
    id: '/plugins',
    path: '/plugins',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsSpacesRoute =
  AuthenticatedSettingsSpacesRouteImport.update({
    id: '/spaces',
    path: '/spaces',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsSystemRoute =
  AuthenticatedSettingsSystemRouteImport.update({
    id: '/system',
    path: '/system',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsTokensRoute =
  AuthenticatedSettingsTokensRouteImport.update({
    id: '/tokens',
    path: '/tokens',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedTrashSpaceIdRoute =
  AuthenticatedTrashSpaceIdRouteImport.update({
    id: '/trash/$spaceId',
    path: '/trash/$spaceId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWBranchIdRoute = AuthenticatedWBranchIdRouteImport.update({
  id: '/w/$branchId',
  path: '/w/$branchId',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/health': typeof AuthenticatedHealthRoute
  '/pinned': typeof AuthenticatedPinnedRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/login': typeof PublicLoginRoute
  '/lenses/$lensId': typeof AuthenticatedLensesLensIdRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/danger': typeof AuthenticatedSettingsDangerRoute
  '/settings/groups': typeof AuthenticatedSettingsGroupsRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/settings/maintenance': typeof AuthenticatedSettingsMaintenanceRoute
  '/settings/plugins': typeof AuthenticatedSettingsPluginsRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/spaces': typeof AuthenticatedSettingsSpacesRoute
  '/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/settings/tokens': typeof AuthenticatedSettingsTokensRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/trash/$spaceId': typeof AuthenticatedTrashSpaceIdRoute
  '/w/$branchId': typeof AuthenticatedWBranchIdRoute
  '/lenses/': typeof AuthenticatedLensesIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/health': typeof AuthenticatedHealthRoute
  '/pinned': typeof AuthenticatedPinnedRoute
  '/login': typeof PublicLoginRoute
  '/lenses/$lensId': typeof AuthenticatedLensesLensIdRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/danger': typeof AuthenticatedSettingsDangerRoute
  '/settings/groups': typeof AuthenticatedSettingsGroupsRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/settings/maintenance': typeof AuthenticatedSettingsMaintenanceRoute
  '/settings/plugins': typeof AuthenticatedSettingsPluginsRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/spaces': typeof AuthenticatedSettingsSpacesRoute
  '/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/settings/tokens': typeof AuthenticatedSettingsTokensRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/trash/$spaceId': typeof AuthenticatedTrashSpaceIdRoute
  '/w/$branchId': typeof AuthenticatedWBranchIdRoute
  '/lenses': typeof AuthenticatedLensesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authenticated/health': typeof AuthenticatedHealthRoute
  '/_authenticated/pinned': typeof AuthenticatedPinnedRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/lenses/$lensId': typeof AuthenticatedLensesLensIdRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/danger': typeof AuthenticatedSettingsDangerRoute
  '/_authenticated/settings/groups': typeof AuthenticatedSettingsGroupsRoute
  '/_authenticated/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/_authenticated/settings/maintenance': typeof AuthenticatedSettingsMaintenanceRoute
  '/_authenticated/settings/plugins': typeof AuthenticatedSettingsPluginsRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/settings/spaces': typeof AuthenticatedSettingsSpacesRoute
  '/_authenticated/settings/system': typeof AuthenticatedSettingsSystemRoute
  '/_authenticated/settings/tokens': typeof AuthenticatedSettingsTokensRoute
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/_authenticated/trash/$spaceId': typeof AuthenticatedTrashSpaceIdRoute
  '/_authenticated/w/$branchId': typeof AuthenticatedWBranchIdRoute
  '/_authenticated/lenses/': typeof AuthenticatedLensesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/pinned'
    | '/settings'
    | '/login'
    | '/lenses/$lensId'
    | '/settings/appearance'
    | '/settings/danger'
    | '/settings/groups'
    | '/settings/integrations'
    | '/settings/maintenance'
    | '/settings/plugins'
    | '/settings/profile'
    | '/settings/spaces'
    | '/settings/system'
    | '/settings/tokens'
    | '/settings/users'
    | '/trash/$spaceId'
    | '/w/$branchId'
    | '/lenses/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/pinned'
    | '/login'
    | '/lenses/$lensId'
    | '/settings/appearance'
    | '/settings/danger'
    | '/settings/groups'
    | '/settings/integrations'
    | '/settings/maintenance'
    | '/settings/plugins'
    | '/settings/profile'
    | '/settings/spaces'
    | '/settings/system'
    | '/settings/tokens'
    | '/settings/users'
    | '/trash/$spaceId'
    | '/w/$branchId'
    | '/lenses'
    | '/settings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/health'
    | '/_authenticated/pinned'
    | '/_authenticated/settings'
    | '/_public/login'
    | '/_authenticated/'
    | '/_authenticated/lenses/$lensId'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/danger'
    | '/_authenticated/settings/groups'
    | '/_authenticated/settings/integrations'
    | '/_authenticated/settings/maintenance'
    | '/_authenticated/settings/plugins'
    | '/_authenticated/settings/profile'
    | '/_authenticated/settings/spaces'
    | '/_authenticated/settings/system'
    | '/_authenticated/settings/tokens'
    | '/_authenticated/settings/users'
    | '/_authenticated/trash/$spaceId'
    | '/_authenticated/w/$branchId'
    | '/_authenticated/lenses/'
    | '/_authenticated/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/health': {
      id: '/_authenticated/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AuthenticatedHealthRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pinned': {
      id: '/_authenticated/pinned'
      path: '/pinned'
      fullPath: '/pinned'
      preLoaderRoute: typeof AuthenticatedPinnedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/lenses/': {
      id: '/_authenticated/lenses/'
      path: '/lenses'
      fullPath: '/lenses/'
      preLoaderRoute: typeof AuthenticatedLensesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lenses/$lensId': {
      id: '/_authenticated/lenses/$lensId'
      path: '/lenses/$lensId'
      fullPath: '/lenses/$lensId'
      preLoaderRoute: typeof AuthenticatedLensesLensIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/danger': {
      id: '/_authenticated/settings/danger'
      path: '/danger'
      fullPath: '/settings/danger'
      preLoaderRoute: typeof AuthenticatedSettingsDangerRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/groups': {
      id: '/_authenticated/settings/groups'
      path: '/groups'
      fullPath: '/settings/groups'
      preLoaderRoute: typeof AuthenticatedSettingsGroupsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/integrations': {
      id: '/_authenticated/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AuthenticatedSettingsIntegrationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/maintenance': {
      id: '/_authenticated/settings/maintenance'
      path: '/maintenance'
      fullPath: '/settings/maintenance'
      preLoaderRoute: typeof AuthenticatedSettingsMaintenanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/plugins': {
      id: '/_authenticated/settings/plugins'
      path: '/plugins'
      fullPath: '/settings/plugins'
      preLoaderRoute: typeof AuthenticatedSettingsPluginsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/spaces': {
      id: '/_authenticated/settings/spaces'
      path: '/spaces'
      fullPath: '/settings/spaces'
      preLoaderRoute: typeof AuthenticatedSettingsSpacesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/system': {
      id: '/_authenticated/settings/system'
      path: '/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof AuthenticatedSettingsSystemRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/tokens': {
      id: '/_authenticated/settings/tokens'
      path: '/tokens'
      fullPath: '/settings/tokens'
      preLoaderRoute: typeof AuthenticatedSettingsTokensRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/trash/$spaceId': {
      id: '/_authenticated/trash/$spaceId'
      path: '/trash/$spaceId'
      fullPath: '/trash/$spaceId'
      preLoaderRoute: typeof AuthenticatedTrashSpaceIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/w/$branchId': {
      id: '/_authenticated/w/$branchId'
      path: '/w/$branchId'
      fullPath: '/w/$branchId'
      preLoaderRoute: typeof AuthenticatedWBranchIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDangerRoute: typeof AuthenticatedSettingsDangerRoute
  AuthenticatedSettingsGroupsRoute: typeof AuthenticatedSettingsGroupsRoute
  AuthenticatedSettingsIntegrationsRoute: typeof AuthenticatedSettingsIntegrationsRoute
  AuthenticatedSettingsMaintenanceRoute: typeof AuthenticatedSettingsMaintenanceRoute
  AuthenticatedSettingsPluginsRoute: typeof AuthenticatedSettingsPluginsRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSettingsSpacesRoute: typeof AuthenticatedSettingsSpacesRoute
  AuthenticatedSettingsSystemRoute: typeof AuthenticatedSettingsSystemRoute
  AuthenticatedSettingsTokensRoute: typeof AuthenticatedSettingsTokensRoute
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
  AuthenticatedSettingsDangerRoute: AuthenticatedSettingsDangerRoute,
  AuthenticatedSettingsGroupsRoute: AuthenticatedSettingsGroupsRoute,
  AuthenticatedSettingsIntegrationsRoute:
    AuthenticatedSettingsIntegrationsRoute,
  AuthenticatedSettingsMaintenanceRoute: AuthenticatedSettingsMaintenanceRoute,
  AuthenticatedSettingsPluginsRoute: AuthenticatedSettingsPluginsRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedSettingsSpacesRoute: AuthenticatedSettingsSpacesRoute,
  AuthenticatedSettingsSystemRoute: AuthenticatedSettingsSystemRoute,
  AuthenticatedSettingsTokensRoute: AuthenticatedSettingsTokensRoute,
  AuthenticatedSettingsUsersRoute: AuthenticatedSettingsUsersRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedHealthRoute: typeof AuthenticatedHealthRoute
  AuthenticatedPinnedRoute: typeof AuthenticatedPinnedRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedLensesLensIdRoute: typeof AuthenticatedLensesLensIdRoute
  AuthenticatedTrashSpaceIdRoute: typeof AuthenticatedTrashSpaceIdRoute
  AuthenticatedWBranchIdRoute: typeof AuthenticatedWBranchIdRoute
  AuthenticatedLensesIndexRoute: typeof AuthenticatedLensesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHealthRoute: AuthenticatedHealthRoute,
  AuthenticatedPinnedRoute: AuthenticatedPinnedRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedLensesLensIdRoute: AuthenticatedLensesLensIdRoute,
  AuthenticatedTrashSpaceIdRoute: AuthenticatedTrashSpaceIdRoute,
  AuthenticatedWBranchIdRoute: AuthenticatedWBranchIdRoute,
  AuthenticatedLensesIndexRoute: AuthenticatedLensesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
