import { createRouter } from "@tanstack/react-router";

import { routeTree } from "./routeTree.gen";

// Single router instance for the whole app. The route tree is generated by the
// TanStack Router Vite plugin from src/routes/ and type-checked at compile time.
export const router = createRouter({
  routeTree,
  scrollRestoration: true,
  defaultPreload: "intent",
});

declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}
